apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: demo-service
  description: "Dịch vụ dùng để demo Global Map"
  annotations:
    backstage.io/techdocs-ref: dir:./docs
spec:
  type: service
  owner: rde-dev-team
  system: demo-system
  lifecycle: production
  providesApis:
    - demo-api
  consumesApis:
    - content-api
  dependsOn:
    - component:content-service
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-api
spec:
  type: openapi
  lifecycle: production
  owner: rde-dev-team
  definition:
    $text: ./api/openapi.yaml