site_name: Demo Service Documentation
site_description: >-
  Tài liệu chi tiết về cấu trúc tích hợp, mã lỗi và các endpoint gửi nhận SMS.
nav:
  - Home: index.md
  - Architecture: architecture.md
  - API: api.md
  - Deployment: deployment.md
  - Configuration: configuration.md
  - Database: database.md
  - Security: security.md
  - Monitoring: monitoring.md
  - Runbook: runbook.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md
  - Changelog: changelog.md
plugins:
  - techdocs-core
  - mermaid2:
      arguments:
        theme: default # Các theme: default, dark, neutral, forest

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
